export const homeObjOne = {
  id: "about",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "Previem",
  headline: "Unlimited transiction from zero",
  description: "Get access to exclusive app for publish anything for enojy.",
  buttonLabel: "Send email",
  imgStart: false,
  img: require("../../assets/svg1.svg"),
  alt: "Card",
  dark: true,
  primary: true,
  darkText: false,
};
